# -*- coding: utf-8 -*-
"""Hello world

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LwgXOgVpTWKPcLCZ_CfTOpzm72kqFOp
"""

print ("hello world")